### ISSUE TITLE
[Refactor] API 변경에 따른 결제 부분 코드 변경

### ISSUE THREAD

**Issue by seacrab808** [Shimpyo-House/Shimpyo_FE#110]
## Description

백엔드 API 작업이 완료 되면 그에 맞게 프론트 코드도 변경하려 합니다
기존 리코일로 받았던 정보를 백에서 get하고 그 정보를 post 하게 할 계획입니다

## Todo

- [ ] get 하는 api 연결
- [ ] 리코일 데이터 get 데이터로 변경
- [ ] post 하는 리코일 데이터 get 데이터로 변경
- [ ] 결제 완료 페이지 get 데이터로 변경
- [ ] 전체 예약 내역 페이지 수정

## ETC

아직 백 로직이 완성되지 않아서 대기중입니다
