### ISSUE TITLE
[Feat] 숙소상세페이지 추가작업

### ISSUE THREAD

**Issue by jiohjung98** [Shimpyo-House/Shimpyo_FE#114]
## Description

숙소상세페이지 추가작업

## Todo

- [ ] 숙소 추가 정보 페이지 추가
- [ ] 룸 추가 정보 페이지 추가
- [ ] 룸 컨테이너 수정(룸 이미지 캐러셀(슬라이더)로 변경&룸 개수 카운트 UI)
- [ ] 장바구니 api 수정
- [ ] 상세페이지 주소 기준 주변 숙소 찾는 기능(optional)

## ETC

즐겨찾기가 숙소 즐겨찾기인지 룸 즐겨찾기인지? 모르겠네요?
