### ISSUE TITLE
[Feat] 숙소상세페이지 새로운 데이터 적용

### ISSUE THREAD

**Issue by jiohjung98** [Shimpyo-House/Shimpyo_FE#119]
## Description

숙소상세페이지 새로운 데이터 적용

## Todo

- [x] 숙소 정보 추가(룸 컨테이너 아래)
- [x]  룸 컨테이너 수정(룸 이미지 캐러셀(슬라이더)로 변경&룸 개수 카운트 UI)
- [ ]  상세페이지 주소 기준 주변 숙소 찾는 기능(optional)
