### ISSUE TITLE
[Refactor] 결제 완료/예약내역확인 페이지 API data 변경

### ISSUE THREAD

**Issue by seacrab808** [Shimpyo-House/Shimpyo_FE#125]
## Description

결제 완료/예약 내역 확인 페이지 API data 변경

## Todo

- [x] 결제 완료 페이지
- [x] 예약내역확인 페이지
- [x] 결제 페이지 총 금액/박수 구하기
- [x] 결제 페이지 스크롤 상단으로
- [x] 결제 페이지 이름/전화번호 유효성 검사 추가
- [ ] 결제하기 버튼 활성화 요소들 렌더링 추가
- [x] 결제하기 post에 카트 ID 추가
- [x] 결제 취소하기 버튼 생성
