### ISSUE TITLE
[Design] 카테고리 상품 조회 UI 생성

### ISSUE THREAD

**Issue by Yamyam-code** [Shimpyo-House/Shimpyo_FE#13]
## Description
카테고리 상품 조회 UI 생성

## Todo

- [x] 카테고리 UI 컴포넌트 생성
- [x] 카테고리 상품 조회 페이지 생성
- [x] NormalCategry.tsx & useFetchData.ts 이름 수정
