### ISSUE TITLE
[Feat] 결제 페이지 기능 추가 및 보완

### ISSUE THREAD

**Issue by seacrab808** [Shimpyo-House/Shimpyo_FE#32]
## Description

결제 페이지 기능 추가 및 보완

## Todo

- [x] input size up
- [x] 예약자/이용자 유효성 검사 추가
- [x] 체크박스 UI 변경
- [x] 체크하면 예약자 정보 -> 이용자 input
- [x] 전화번호 010-0000-0000 "-" 추가
