### ISSUE TITLE
[Feat/Design] 결제 수단/요청 사항 추가, 결제 페이지 로딩 추가

### ISSUE THREAD

**Issue by seacrab808** [Shimpyo-House/Shimpyo_FE#44]
## Description

결제 수단 부분 추가하려고 합니닷 4-5개 정도?
<img src="https://github.com/Shimpyo-House/Shimpyo_FE/assets/93272421/f94ba7d7-f759-427a-953b-f547f44b98e8" alt="이미지" />

- 결제 로딩 이미지
<img src="https://github.com/Shimpyo-House/Shimpyo_FE/assets/93272421/d3a0667c-9c33-41e3-8eb2-2a654bc2991d" alt="이미지" />

## Todo

- [x] 결제 수단 컴포넌트 UI 
- [x] 결제 완료 페이지에 결제 수단 항목 추가
- [x] 결제 페이지에서 넘어가야 하는 데이터 쿠키나 로컬 스토리지로 데이터 넘기기
- [x] 결제 페이지 진입 시 결제 중 로딩 추가

## ETC
- 데이터 넘길 때 리코일도 고려하고 있는데, 가장 적합한 것으로 골라 하겠습니당
(어제 이 이슈 썼는데 날라갔네 .. 흑ㅎ긓....)
분리해서 할 수 있긴 한데 기능이 다 연결되어있어서 한 이슈로 하겟슘니당 
- 마감 예상 : 11/27 오후 or 11/28 새벽
