### ISSUE TITLE
[Feat] 백엔드 데이터 연결

### ISSUE THREAD

**Issue by seacrab808** [Shimpyo-House/Shimpyo_FE#51]
## Description
백엔드 데이터 연결

## Todo
- [x] 장바구니에서 넘어오는 전역 데이터 연결
- [x] 결제 API 연결
- [x] 이용자 정보, 결제 수단, 방문 수단 백엔드로 데이터 넘기기
- [x] 예약 내역 API 데이터 연결, 방문 수단 추가

## ETC
내일 오후/새벽까지 가능할 것 같습니당
