### ISSUE TITLE
[Feat] 장바구니 DELETE - 백엔드 API 연결

### ISSUE THREAD

**Issue by wkdtnqls0506** [Shimpyo-House/Shimpyo_FE#54]
## Description

- 장바구니 - 백엔드 API 연결

## Todo
- [x] 장바구니 DELETE
     - [x] 실제 API 연결
     - [x] 아이템 삭제시 UI에 즉시 반영
     - [x] 리액트 쿼리를 사용하여 장바구니 관련 API hook화
