### ISSUE TITLE
[Feat] 장바구니 예약 가능 여부 - 백엔드 API 연결

### ISSUE THREAD

**Issue by wkdtnqls0506** [Shimpyo-House/Shimpyo_FE#61]
## Description
- 장바구니 예약 가능 여부 로직 작성

## Todo

- [x] 장바구니 예약 가능 여부 로직 작성
     - [x] 백엔드 API 연결
     - [x] 전역변수에 주문 가능한 데이터 담기
