### ISSUE TITLE
[Feat] 숙소상세페이지 디자인 작업

### ISSUE THREAD

**Issue by jiohjung98** [Shimpyo-House/Shimpyo_FE#64]
## Description

숙소상세페이지 디자인 

## Todo

- [ ] 방 정보 디자인 재작업
- [ ] 장바구니 넣을 시, 헤더 장바구니 숫자 변경
- [ ] 로그인 x -> 장바구니, 예약하기 버튼 클릭 시 알랄트
- [ ] 예약하기 버튼 결제페이지 연결
- [ ] 방이미지 정보 없어서 어떻게 처리할 지 고민
