### ISSUE TITLE
[Chore] index.html 수정, 비동기 로딩바 연결, README 초안 작성

### ISSUE THREAD

**Issue by TaePoong719** [Shimpyo-House/Shimpyo_FE#65]
## Description
배포 전 자잘한 것 이것 저것

## Todo

- [ ] index.html 수정
- [ ] 비동기 로딩바 연결
- [ ] README 초안 작성
